
import React, { useState, useEffect, useRef } from 'react';
import { useLocation, useNavigate } from 'react-router-dom';
import { getPatientCases, getCaseAnalysisDetails } from '../../services/mockBackend';
import { PatientCase, AnalysisType, MultiModalAnalysis } from '../../types';
import { useAuth } from '../../App';
import { chatWithMedora } from '../../services/geminiService';
import { 
  BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, Legend, ResponsiveContainer, 
  ScatterChart, Scatter, ZAxis, ReferenceLine, Cell, RadarChart, PolarGrid, PolarAngleAxis, PolarRadiusAxis, Radar,
  LineChart, Line
} from 'recharts';
import { 
  Dna, Activity, Brain, FileText, Image as ImageIcon, Share2, Sparkles, 
  TestTube, Microscope, Download, MessageSquare, X, CheckCircle, Info, AlertTriangle, File, Send
} from 'lucide-react';
import ReactMarkdown from 'react-markdown'; 
import html2canvas from 'html2canvas';
import { jsPDF } from 'jspdf';

const CaseAnalysis = () => {
  const { user } = useAuth();
  const location = useLocation();
  const navigate = useNavigate();
  const reportRef = useRef<HTMLDivElement>(null);
  
  const [selectedCase, setSelectedCase] = useState<PatientCase | null>(null);
  const [analysisData, setAnalysisData] = useState<MultiModalAnalysis | null>(null);
  const [isExporting, setIsExporting] = useState(false);
  
  const [activeModes, setActiveModes] = useState({
    genomic: true,
    ehr: true,
    imaging: false,
    proteomic: false
  });

  const [medoraOpen, setMedoraOpen] = useState(false);
  const [medoraHistory, setMedoraHistory] = useState<{role: 'user' | 'model', text: string}[]>([]);
  const [medoraInput, setMedoraInput] = useState('');
  const [medoraLoading, setMedoraLoading] = useState(false);

  useEffect(() => {
    if (user) {
      const state = location.state as { caseId?: string };
      if (state?.caseId) {
        const details = getCaseAnalysisDetails(state.caseId);
        const patients = getPatientCases(user.email);
        const patient = patients.find(p => p.id === state.caseId);
        
        setSelectedCase(patient || null);
        setAnalysisData(details);
        
        setMedoraHistory([
          { role: 'model', text: `Diagnostic workspace initialized for ${patient?.patientName}. AI confidence for **${details.predictions[0].diseaseName}** is ${details.predictions[0].probability * 100}%. How can I assist with the results?` }
        ]);
      }
    }
  }, [user, location.state]);

  const handleExportPDF = async () => {
    if (!reportRef.current) return;
    setIsExporting(true);
    try {
      const canvas = await html2canvas(reportRef.current, { scale: 2 });
      const imgData = canvas.toDataURL('image/png');
      const pdf = new jsPDF({ orientation: 'p', unit: 'mm', format: 'a4' });
      const width = pdf.internal.pageSize.getWidth();
      const height = (canvas.height * width) / canvas.width;
      pdf.addImage(imgData, 'PNG', 0, 0, width, height);
      pdf.save(`Genosym_Diagnostic_Report_${selectedCase?.id}.pdf`);
    } finally {
      setIsExporting(false);
    }
  };

  const handleExportWord = () => {
    const content = `
      <html xmlns:o='urn:schemas-microsoft-com:office:office' xmlns:w='urn:schemas-microsoft-com:office:word' xmlns='http://www.w3.org/TR/REC-html40'>
      <head><meta charset='utf-8'><title>Diagnostic Report</title></head>
      <body style='font-family: Arial, sans-serif;'>
        <h1 style='color: #0c4a6e;'>Genosym AI - Clinical Diagnostic Report</h1>
        <hr/>
        <h2>Patient: ${selectedCase?.patientName}</h2>
        <p><strong>Case ID:</strong> ${selectedCase?.id} | <strong>Age:</strong> ${selectedCase?.age}</p>
        <p><strong>Primary Diagnosis:</strong> ${analysisData?.diseaseProfile.name}</p>
        <p><strong>AI Confidence:</strong> ${(analysisData?.predictions[0].probability! * 100).toFixed(1)}%</p>
        <hr/>
        <h3>Disease Summary</h3>
        <p>${analysisData?.diseaseProfile.summary}</p>
        <h3>AI Explainability (SHAP Analysis)</h3>
        <p>${analysisData?.diseaseProfile.explainability}</p>
        <hr/>
        <h3>Recommended Protocol</h3>
        <ul>${analysisData?.diseaseProfile.treatment.map(t => `<li>${t}</li>`).join('')}</ul>
        <br/>
        <p style='font-size: 10px; color: gray;'>Generated by Genosym-AI Trusted Intelligence. Clinical validation required.</p>
      </body>
      </html>
    `;
    const blob = new Blob(['\ufeff', content], { type: 'application/msword' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `Genosym_Report_${selectedCase?.id}.doc`;
    link.click();
  };

  if (!selectedCase || !analysisData) return null;

  return (
    <div className="flex flex-col lg:flex-row h-screen overflow-hidden bg-slate-50 font-sans">
      <div className="w-full lg:w-80 bg-white border-r border-slate-200 overflow-y-auto p-6 flex flex-col gap-8 no-print">
        <div>
          <h2 className="text-xs font-black text-slate-400 uppercase tracking-widest mb-4">Multi-Modal Prediction</h2>
          <div className="space-y-3">
            {[
              { id: 'genomic', label: 'Genomic Engine', icon: <Dna className="w-4 h-4" /> },
              { id: 'ehr', label: 'Clinical NLP', icon: <FileText className="w-4 h-4" /> },
              { id: 'imaging', label: 'Radiology Heatmap', icon: <ImageIcon className="w-4 h-4" /> },
              { id: 'proteomic', label: 'Serum Biomarkers', icon: <Activity className="w-4 h-4" /> }
            ].map(mode => (
              <button 
                key={mode.id}
                onClick={() => setActiveModes(prev => ({ ...prev, [mode.id]: !prev[mode.id as keyof typeof activeModes] }))}
                className={`w-full flex items-center justify-between p-3.5 rounded-2xl border-2 transition-all ${activeModes[mode.id as keyof typeof activeModes] ? 'border-primary-600 bg-primary-50 text-primary-700 shadow-sm' : 'border-slate-100 bg-slate-50 text-slate-500'}`}
              >
                <div className="flex items-center gap-3">
                  {mode.icon}
                  <span className="text-xs font-black uppercase tracking-tight">{mode.label}</span>
                </div>
                <div className={`w-8 h-4 rounded-full relative transition-colors ${activeModes[mode.id as keyof typeof activeModes] ? 'bg-primary-600' : 'bg-slate-300'}`}>
                   <div className={`absolute top-0.5 w-3 h-3 bg-white rounded-full transition-transform ${activeModes[mode.id as keyof typeof activeModes] ? 'left-4' : 'left-1'}`} />
                </div>
              </button>
            ))}
          </div>
        </div>

        <div>
          <h2 className="text-xs font-black text-slate-400 uppercase tracking-widest mb-4">Clinical Export</h2>
          <div className="grid grid-cols-2 gap-3">
            <button onClick={handleExportPDF} className="p-4 bg-slate-900 text-white rounded-2xl flex flex-col items-center gap-2 hover:bg-black transition shadow-lg">
               <File className="w-5 h-5 text-red-400" />
               <span className="text-[10px] font-black uppercase">PDF Report</span>
            </button>
            <button onClick={handleExportWord} className="p-4 bg-slate-100 border border-slate-200 text-slate-700 rounded-2xl flex flex-col items-center gap-2 hover:bg-slate-200 transition">
               <FileText className="w-5 h-5 text-blue-500" />
               <span className="text-[10px] font-black uppercase">Word Doc</span>
            </button>
          </div>
        </div>
      </div>

      <div className="flex-1 overflow-y-auto custom-scroll p-8 space-y-8" ref={reportRef}>
        <div className="bg-white p-8 rounded-[2.5rem] shadow-sm border border-slate-200 flex flex-col md:flex-row justify-between gap-8 items-center">
          <div className="flex items-center gap-6">
            <div className="w-20 h-20 bg-primary-100 rounded-[1.5rem] flex items-center justify-center text-primary-600 font-black text-3xl shadow-inner">
              {selectedCase.patientName.charAt(0)}
            </div>
            <div>
              <h1 className="text-3xl font-black text-slate-900 tracking-tight">{selectedCase.patientName}</h1>
              <p className="text-slate-500 font-bold uppercase text-xs tracking-widest">{selectedCase.id} • {selectedCase.age}y • {selectedCase.gender}</p>
              <div className="mt-3 flex gap-2">
                {selectedCase.symptoms.map(s => <span key={s} className="px-3 py-1 bg-slate-100 rounded-full text-[10px] font-black uppercase text-slate-600 border border-slate-200">{s}</span>)}
              </div>
            </div>
          </div>
          <div className="text-center md:text-right border-l md:border-l-0 md:pl-0 pl-8 border-slate-100">
             <p className="text-[10px] font-black text-slate-400 uppercase tracking-widest mb-1">AI Prediction Output</p>
             <p className="text-2xl font-black text-primary-700 tracking-tight">{analysisData.predictions[0].diseaseName}</p>
             <p className="text-4xl font-black text-emerald-600 tracking-tighter">{(analysisData.predictions[0].probability * 100).toFixed(0)}% <span className="text-xs font-bold text-slate-400 tracking-normal">CONFIDENCE</span></p>
          </div>
        </div>

        {/* Explainability and Summary Sections */}
        <div className="grid grid-cols-1 xl:grid-cols-2 gap-8">
           <div className={`bg-white p-8 rounded-[2rem] border border-slate-200 shadow-sm transition-opacity ${activeModes.genomic ? 'opacity-100' : 'opacity-30 grayscale pointer-events-none'}`}>
              <h3 className="text-lg font-black text-slate-800 mb-6 flex items-center gap-3">
                <Dna className="text-blue-500 w-5 h-5" /> AI Explainability (SHAP)
              </h3>
              <div className="h-64">
                <ResponsiveContainer width="100%" height="100%">
                   <BarChart data={analysisData.shapValues.filter(s => s.category === 'Genomic')}>
                      <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#f1f5f9" />
                      <XAxis dataKey="feature" fontSize={11} fontWeight="bold" />
                      <YAxis hide />
                      <Tooltip />
                      <Bar dataKey="impact" radius={[8, 8, 0, 0]} fill="#3b82f6">
                         {analysisData.shapValues.map((entry, index) => (
                           <Cell key={`cell-${index}`} fill={entry.impact > 0.5 ? '#2563eb' : '#60a5fa'} />
                         ))}
                      </Bar>
                   </BarChart>
                </ResponsiveContainer>
              </div>
              <div className="mt-6 bg-slate-50 p-6 rounded-2xl border border-slate-200">
                <h4 className="text-xs font-black text-slate-400 uppercase mb-2">Model Reasoning</h4>
                <p className="text-sm text-slate-700 font-medium leading-relaxed italic border-l-4 border-primary-500 pl-4">
                  {analysisData.diseaseProfile.explainability}
                </p>
              </div>
           </div>

           <div className={`bg-white p-8 rounded-[2rem] border border-slate-200 shadow-sm transition-opacity ${activeModes.proteomic ? 'opacity-100' : 'opacity-30 grayscale pointer-events-none'}`}>
              <h3 className="text-lg font-black text-slate-800 mb-6 flex items-center gap-3">
                <Activity className="text-teal-500 w-5 h-5" /> Disease Synthesis Summary
              </h3>
              <div className="h-64">
                <ResponsiveContainer width="100%" height="100%">
                   <RadarChart cx="50%" cy="50%" outerRadius="80%" data={analysisData.clinicalBiomarkers}>
                      <PolarGrid stroke="#e2e8f0" />
                      <PolarAngleAxis dataKey="name" fontSize={10} fontWeight="black" />
                      <Radar name="Level" dataKey="value" stroke="#0d9488" fill="#0d9488" fillOpacity={0.4} />
                      <Tooltip />
                   </RadarChart>
                </ResponsiveContainer>
              </div>
              <div className="mt-6 space-y-4">
                 <h4 className="text-xs font-black text-slate-400 uppercase">Clinical Overview</h4>
                 <div className="bg-teal-50 p-6 rounded-2xl border border-teal-100 font-medium text-slate-700 text-sm leading-relaxed">
                   {analysisData.diseaseProfile.summary}
                 </div>
              </div>
           </div>
        </div>

        <div className="bg-white rounded-[2rem] border border-slate-200 overflow-hidden shadow-sm">
           <div className="px-10 py-6 border-b border-slate-100 bg-slate-50/50">
             <h3 className="font-black text-slate-800 uppercase text-xs tracking-widest">Recommended Treatment Protocol</h3>
           </div>
           <table className="w-full text-left">
              <thead className="bg-slate-50">
                <tr>
                  <th className="px-10 py-5 text-[10px] font-black text-slate-400 uppercase tracking-widest">Intervention</th>
                  <th className="px-10 py-5 text-[10px] font-black text-slate-400 uppercase tracking-widest">AI Proposed Care Path</th>
                  <th className="px-10 py-5 text-right text-[10px] font-black text-slate-400 uppercase tracking-widest">Clinical Confidence</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-100">
                <tr>
                   <td className="px-10 py-6 text-xs font-black text-slate-600 uppercase">Pharmacotherapy</td>
                   <td className="px-10 py-6 text-sm font-black text-primary-700">{analysisData.diseaseProfile.treatment[0]}</td>
                   <td className="px-10 py-6 text-right"><span className="text-[10px] font-black bg-blue-100 text-blue-800 px-3 py-1.5 rounded-full uppercase tracking-tighter shadow-sm">HIGH_EVIDENCE</span></td>
                </tr>
                <tr>
                   <td className="px-10 py-6 text-xs font-black text-slate-600 uppercase">Dietary Control</td>
                   <td className="px-10 py-6 text-sm text-slate-700 font-bold">{analysisData.diseaseProfile.treatment[1]}</td>
                   <td className="px-10 py-6 text-right"><span className="text-[10px] font-black bg-emerald-100 text-emerald-800 px-3 py-1.5 rounded-full uppercase tracking-tighter shadow-sm">STANDARD_CARE</span></td>
                </tr>
              </tbody>
           </table>
        </div>
      </div>

      <button onClick={() => setMedoraOpen(!medoraOpen)} className="fixed bottom-8 right-8 w-16 h-16 bg-gradient-to-br from-primary-600 to-indigo-700 rounded-[1.5rem] shadow-2xl flex items-center justify-center text-white hover:scale-110 transition active:scale-95 no-print z-[100]">
        <Sparkles className="w-8 h-8" />
      </button>

      {medoraOpen && (
        <div className="fixed inset-y-0 right-0 w-[28rem] bg-white shadow-2xl z-[110] border-l border-slate-200 flex flex-col animate-slide-in no-print">
           <div className="p-8 bg-slate-900 text-white flex justify-between items-center shadow-lg">
             <div className="flex items-center gap-4">
                <div className="p-2 bg-primary-500 rounded-xl"><Sparkles className="w-6 h-6 text-white" /></div>
                <div>
                  <h3 className="font-black tracking-tight text-xl">Medora Diagnostic</h3>
                  <p className="text-[10px] font-bold text-primary-300 uppercase tracking-widest">Active Consultation</p>
                </div>
             </div>
             <button onClick={() => setMedoraOpen(false)} className="hover:bg-white/10 p-2 rounded-full transition"><X className="w-6 h-6" /></button>
           </div>
           <div className="flex-1 overflow-y-auto p-8 space-y-8 custom-scroll bg-slate-50">
             {medoraHistory.map((h, i) => (
               <div key={i} className={`flex ${h.role === 'model' ? 'justify-start' : 'justify-end'}`}>
                  <div className={`max-w-[90%] p-5 rounded-[1.5rem] text-sm leading-relaxed shadow-sm ${h.role === 'model' ? 'bg-white text-slate-800 border border-slate-200 rounded-bl-none' : 'bg-primary-600 text-white rounded-br-none'}`}>
                    <ReactMarkdown>{h.text}</ReactMarkdown>
                  </div>
               </div>
             ))}
             {medoraLoading && <div className="flex justify-start"><div className="p-4 bg-white rounded-2xl shadow-inner italic text-xs text-slate-400">Processing medical context...</div></div>}
           </div>
           <div className="p-6 border-t bg-white shadow-inner">
             <div className="flex gap-3">
                <input 
                  value={medoraInput} 
                  onChange={e => setMedoraInput(e.target.value)} 
                  onKeyDown={e => e.key === 'Enter' && handleMedoraSend()}
                  placeholder="Explain mutation impact..." 
                  className="flex-1 p-4 bg-slate-100 rounded-2xl text-sm outline-none focus:ring-2 focus:ring-primary-500 font-medium text-slate-900"
                />
                <button onClick={handleMedoraSend} className="p-4 bg-primary-600 text-white rounded-2xl hover:bg-primary-700 transition shadow-lg"><Send className="w-5 h-5" /></button>
             </div>
           </div>
        </div>
      )}
    </div>
  );

  async function handleMedoraSend() {
    if (!medoraInput.trim()) return;
    const msg = medoraInput;
    setMedoraInput('');
    setMedoraHistory(prev => [...prev, { role: 'user', text: msg }]);
    setMedoraLoading(true);
    const res = await chatWithMedora(medoraHistory, msg, 'medical', JSON.stringify(selectedCase));
    setMedoraHistory(prev => [...prev, { role: 'model', text: res || 'Consultation error encountered.' }]);
    setMedoraLoading(false);
  }
};

export default CaseAnalysis;
